Fix style to main
StemVibrations/STEM pull request #254
Opened 2024-10-15 11:17 UTC by aronnoordam

2024-10-21 14:04 UTC, brunozc requested changes

2024-10-21 14:04 UTC, brunozc commented on tests/test_model.py
> +            'input_dir') / model_copy.output_settings[-1].output_dir / model_copy.output_settings[-1].output_name
```suggestion
        expected_path = Path('input_dir', model_copy.output_settings[-1].output_dir, model_copy.output_settings[-1].output_name)
```

2024-10-21 14:04 UTC, brunozc commented on tests/test_stem.py
> +        Test the finalise method of the Stem class with JsonOutputParameters and checks the order of the keys in the dictioary.
``
```suggestion
        Test the finalise method of the Stem class with JsonOutputParameters and checks the order of the keys in the dictionary.
```

2024-10-25 08:26 UTC, aronnoordam commented on benchmark_tests/test_multi_stage_umat/test_multi_stage_umat.py
> +    Note that currently, 2D elements are written with the incremental formulation, and 3D with the full formulation. Different results in multistage analyses are expected
it refers to the 2D plane strain linear elastic constitutive law, 

the stressvector in this law is calculated as follows:

`    mDeltaStrainVector = rValues.GetStrainVector() - mStrainVectorFinalized;

    Matrix C;
    this->CalculateElasticMatrix(C, rValues);

    // Incremental formulation
    noalias(mStressVector) = mStressVectorFinalized + prod(C, mDeltaStrainVector);

    rStressVector = mStressVector;`

2024-10-25 08:27 UTC, aronnoordam commented on benchmark_tests/test_multi_stage_umat/test_multi_stage_umat.py
> +    Note that currently, 2D elements are written with the incremental formulation, and 3D with the full formulation. Different results in multistage analyses are expected
i will change the comment

2024-10-25 08:29 UTC, aronnoordam commented on stem/model.py
> +    def finalise(self, input_folder: str):
maybe in the future more stuff has to be finalised, now the structure is already in place

2024-10-25 08:35 UTC, aronnoordam commented on benchmark_tests/test_multi_stage_dynamic_to_static/test_multistage_dynamic_to_static.py
> +    model_stage_2.project_parameters.settings.rayleigh_k = 0.0
kraton will perform a dynamic calculation with only a damping matrix, and now mass. Maybe we should prevent this behaviour to never use this solver?

2024-10-25 08:59 UTC, aronnoordam commented on tests/test_model.py
> +            'input_dir') / model_copy.output_settings[-1].output_dir / model_copy.output_settings[-1].output_name
this follows from the linter

2024-10-25 09:16 UTC, brunozc commented on benchmark_tests/test_multi_stage_dynamic_to_static/test_multistage_dynamic_to_static.py
> +    model_stage_2.project_parameters.settings.rayleigh_k = 0.0
Create an issue to address this

2024-10-25 09:21 UTC, brunozc approved these changes

2024-10-25 09:30 UTC, merged