Vakantie branch
StemVibrations/STEM pull request #64
Opened 2023-07-18 11:36 UTC by aronnoordam

to be merged after holidays

2023-08-18 15:05 UTC, brunozc requested changes

2023-08-18 15:05 UTC, brunozc commented on tests/test_plot_utils.py
This tests can be changes to make sure that they run in CI/CD.
instead of show, write to eps and compare eps files that are added to test_data. eps is ascii so makes it possible to compare.

2023-08-18 15:08 UTC, aronnoordam commented on run_stem/demo_run_kratos_model.py
> +os.chdir(project_folder)
this is a temporary function, which is to be removed

2023-08-18 15:09 UTC, aronnoordam commented on stem/IO/kratos_additional_processes_io.py
>  class KratosAdditionalProcessesIO:
it is meant for other processes than boundaries and loads. Like: Random fields, excavations

2023-08-21 08:22 UTC, aronnoordam commented on stem/IO/kratos_boundaries_io.py
> +        `value = [float, 0, float]`
0 is required for kratos. Table overrules value

2023-08-21 08:26 UTC, aronnoordam commented on stem/IO/kratos_boundaries_io.py
> +            raise ValueError(f"Attribute `value` is not implemented by class {parameters.__class__.__name__}.")
not exist

2023-08-21 09:07 UTC, aronnoordam commented on stem/IO/kratos_io.py
> +    def __write_loads_and_constraints(self, model: Model):
reasoning is that its called constraints in kratos

2023-08-21 09:10 UTC, aronnoordam commented on stem/IO/kratos_io.py
> +                _key = "loads_process_list"
it is necessary, because absorbing boundaries should not be placed in the contraints_process_list

2023-08-21 09:34 UTC, aronnoordam commented on stem/IO/kratos_loads_io.py
>          load_dict["Parameters"]["model_part_name"] = f"{self.domain}.{part_name}"
the name is a mandatory input when creating a new model part, and is set as a property without a setter, thus it cannot be changed later and it always exists

2023-08-21 09:59 UTC, aronnoordam commented on stem/IO/kratos_model_io.py
> +FORMAT_FLOAT_LONG: str = " {:.10f}"
no reason, but also no reason to not have it. Changing all tests seems like a waste of time

2023-08-21 11:13 UTC, aronnoordam commented on stem/IO/kratos_model_io.py
> +        # if some process model parts, there's no need for initialisation
this is not the same.

The function firsts checks if some ids are not initialised. If not, it resets everything. In your case, it goes wrong if one of the ids is already initilised before.

2023-08-21 11:14 UTC, aronnoordam commented on stem/IO/kratos_model_io.py
> +        # if some process model parts, there's no need for initialisation
that having said, I don't think there is a need for the user to set the ids. So i remove the check for none completely

2023-08-21 11:15 UTC, aronnoordam commented on stem/IO/kratos_model_io.py
> +        if any(_check_not_initialised):
yes

2023-08-21 11:32 UTC, aronnoordam commented on stem/IO/kratos_model_io.py
> +            raise ValueError("Table id not initialised!")
that would result in "Table id None not initialised"

2023-08-21 11:42 UTC, aronnoordam commented on stem/IO/kratos_model_io.py
> +        # validate part is body model part
only the check for the mesh is duplicated

2023-08-21 12:04 UTC, aronnoordam commented on stem/geometry.py
> +        point = cls(id)
i dont understand this comment

2023-08-21 12:07 UTC, aronnoordam commented on stem/geometry.py
> +        line_id = abs(line_id)
line ids can be negative, if the orrientation if inverted. point ids are always positive

2023-08-21 12:09 UTC, aronnoordam commented on stem/geometry.py
> +        surface_id = abs(surface_id)
surface ids can also be negative in reversed orrientation

2023-08-21 12:17 UTC, aronnoordam commented on stem/geometry.py
> +    def create_geometry_from_geo_data(cls, geo_data: Dict[str,Any]):
what do you mean by enforcing with __getattribute__? we can just check if class is initialised already with a bool

2023-08-21 12:38 UTC, aronnoordam commented on stem/geometry.py
>          if ndim_group == 0:
yes

2023-08-21 13:28 UTC, aronnoordam commented on stem/load.py
> +        if analysis_type == AnalysisType.MECHANICAL_GROUNDWATER_FLOW or analysis_type == AnalysisType.MECHANICAL:
to me, this seems a bit overcomplicated to add an extra function for this one line. I think as it is now, it is more clear. All checks are confined per Load

2023-08-21 13:33 UTC, aronnoordam commented on stem/mesh.py
> +        - element_shape (:class:`ElementShape`): The element shape. TRIANGLE for triangular elements and \
these are the attributes, not the __init__ arguments. The order of both the attributes and arguments are correct

2023-08-21 14:09 UTC, aronnoordam commented on stem/model.py
> +        model_part: Union[ModelPart, BodyModelPart]
no, it is required for mypy

2023-08-21 14:13 UTC, aronnoordam commented on stem/model.py
> +        # todo add validation that load is applied on a body model part
its not done yet, still a todo

2023-08-21 14:35 UTC, aronnoordam commented on stem/model.py
> +        # add gravity load if K0 procedure or gravity loading is used
But that just means, no stress initialisation, which is also an option. I don't understand what you mean

2023-08-21 14:37 UTC, aronnoordam commented on stem/model_part.py
> +    def __init__(self, name: str):
its there?

2023-08-21 14:38 UTC, aronnoordam commented on stem/mesh.py
> +    def __init__(self, element_size: float = -1, element_order: int = 1,
gmsh chooses in case mesh size <0

2023-08-21 14:45 UTC, aronnoordam commented on stem/soil_material.py
> +                element_name = f"SmallStrainUPwDiffOrderElement{n_dim_model}D{n_nodes_element}N"
yes

2023-08-21 14:48 UTC, aronnoordam commented on stem/utils.py
> +class Utils:
I think class is more clear when the functions are called

2023-08-21 15:15 UTC, aronnoordam commented on tests/test_default_materials.py
will do

2023-08-21 15:16 UTC, aronnoordam commented on tests/test_geometry.py
function can be deleted as it is unused

2023-08-21 15:19 UTC, aronnoordam commented on tests/test_kratos_boundaries_io.py
the important part in 3D is add_boundary_condition_by_geometry_ids, which is tested in test_model.py

2023-08-22 08:46 UTC, aronnoordam commented on tests/test_kratos_io.py
> +    @pytest.mark.skipif(IS_LINUX, reason="Linux provides different meshing order. The test is not run on Ubuntu")
#95

2023-08-24 09:25 UTC, brunozc commented on stem/geometry.py
> +        surface_id = abs(surface_id)
but if you add abs they cant.
Do we dont allow negative id? it is not clear this

2023-08-24 09:31 UTC, brunozc commented on stem/mesh.py
> +    def __init__(self, element_size: float = -1, element_order: int = 1,
why do we leave this as an option? 
In my opinion we should enforce the user to assign a mesh size

2023-08-24 09:47 UTC, aronnoordam commented on stem/mesh.py
> +    def __init__(self, element_size: float = -1, element_order: int = 1,
#96

2023-08-24 09:48 UTC, brunozc approved these changes

2023-08-24 09:48 UTC, merged